const fs=require('fs'),path=require('path');const {JSDOM}=require('jsdom');const R='site/reader';
const resolve=u=>{u=String(u).split('?')[0];if(u.startsWith('../'))return path.join('site',u.slice(3));if(u.startsWith('http')){try{u=new URL(u).pathname.replace(/^\//,'');}catch(e){}return path.join(R,u);}return path.join(R,u);};
const dom=new JSDOM(fs.readFileSync(R+'/reader2.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,url:'http://x/',beforeParse(w){w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});w.scrollTo=()=>{};w.Element.prototype.scrollIntoView=()=>{};w.fetch=u=>{const f=resolve(u);let t=null;try{t=fs.readFileSync(f,'utf8');}catch(e){}return Promise.resolve({ok:t!=null,status:t!=null?200:404,json:()=>Promise.resolve(t?JSON.parse(t):{}),text:()=>Promise.resolve(t||'')});};}});
const w=dom.window;const errs=[];w.addEventListener('error',e=>errs.push(e.message||e.error&&e.error.message));
const oce=w.console.error;w.console.error=(...a)=>errs.push('CONSOLE:'+a.join(' '));
(async()=>{await new Promise(r=>setTimeout(r,1000));const rows=()=>[...w.document.querySelectorAll('.row')];
rows().find(r=>r.textContent.trim().startsWith('Khuddakanikāya'))?.click();await new Promise(r=>setTimeout(r,180));
rows().find(r=>r.textContent.trim()==='Suttanipātapāḷi')?.click();await new Promise(r=>setTimeout(r,180));
[...w.document.querySelectorAll('.row')].find(r=>r.textContent.trim()==='3. Mahāvagga')?.click();
await new Promise(r=>setTimeout(r,500));
console.log('errors:',JSON.stringify(errs.slice(0,3)));
console.log('doctitle:',(w.document.querySelector('#doctitle')||{}).textContent);
console.log('.head total:',w.document.querySelectorAll('#scroll .head').length);
console.log('.head.section:',w.document.querySelectorAll('#scroll .head.section').length);
console.log('.gatha total:',w.document.querySelectorAll('#scroll .gatha').length);
console.log('has #p-18Khu01-1109 (Mahā start):',!!w.document.querySelector('#p-18Khu01-1109'));
console.log('has #p-18Khu01-705 (Uraga start, should be sliced OUT):',!!w.document.querySelector('#p-18Khu01-705'));
})();
