const fs=require('fs'),path=require('path');const {JSDOM}=require('jsdom');const R='site/reader';
const resolve=u=>{u=String(u).split('?')[0];if(u.startsWith('../'))return path.join('site',u.slice(3));if(u.startsWith('http')){try{u=new URL(u).pathname.replace(/^\//,'');}catch(e){}return path.join(R,u);}return path.join(R,u);};
const dom=new JSDOM(fs.readFileSync(R+'/reader2.html','utf8'),{runScripts:'dangerously',pretendToBeVisual:true,url:'http://x/',beforeParse(w){w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});w.scrollTo=()=>{};w.Element.prototype.scrollIntoView=()=>{};w.fetch=u=>{const f=resolve(u);let t=null;try{t=fs.readFileSync(f,'utf8');}catch(e){}return Promise.resolve({ok:t!=null,status:t!=null?200:404,json:()=>Promise.resolve(t?JSON.parse(t):{}),text:()=>Promise.resolve(t||'')});};}});
const w=dom.window;
(async()=>{await new Promise(r=>setTimeout(r,1000));const rows=()=>[...w.document.querySelectorAll('.row')];
rows().find(r=>r.textContent.trim().startsWith('Khuddakanikāya'))?.click();await new Promise(r=>setTimeout(r,180));
const sn=rows().find(r=>r.textContent.trim()==='Suttanipātapāḷi');sn.click();await new Promise(r=>setTimeout(r,180));
[...sn.parentElement.querySelectorAll('.row')].find(r=>r.textContent.trim()==='5. Pārāyanavagga')?.click();
await new Promise(r=>setTimeout(r,500));
const txt=(w.document.querySelector('#scroll')||{}).textContent||'';
console.log('Vatthugāthā niṭṭhitā. present:',txt.includes('Vatthugāthā niṭṭhitā.'));
})();
